# Generated by Django 4.2.18 on 2025-01-30 14:13

from django.db import migrations, models
import secrets_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret", secrets_fields.fields.SecretTextField(null=True)),
                ("config", secrets_fields.fields.SecretJSONField(null=True)),
                ("secret_aws", secrets_fields.fields.SecretTextField(null=True)),
                ("config_aws", secrets_fields.fields.SecretJSONField(null=True)),
            ],
        ),
    ]
