# Generated by Django 4.2.18 on 2025-01-31 11:45

from django.db import migrations, models
import secrets_fields.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelJSONAWS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret", secrets_fields.fields.SecretJSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelJSONStatic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret", secrets_fields.fields.SecretJSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelTextAWS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret", secrets_fields.fields.SecretTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ModelTextStatic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret", secrets_fields.fields.SecretTextField(null=True)),
            ],
        ),
    ]
