name: Type checking

on: [pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
  
      - name: Configure Poetry to use the correct Python version
        run: poetry env use python3.12

      - name: Install dependencies
        run: |
          poetry install
    
      - name: Install mypy
        run: pip install mypy

      - uses: tsuyoshicho/action-mypy@v4
